import request from 'supertest';
import { beforeEach, describe, expect, it } from 'vitest';
import { createApp } from '../src/app.js';
import { createTestDatabase, testConfig } from './setup.js';

const profile = { age: 24, gender: 'female', heightCm: 165, weightKg: 55, goal: 'maintain', activityLevel: 'medium', avgSleepHours: 7.5, profileTag: '稳定作息型用户' };
async function register(app, suffix) { const response=await request(app).post('/api/v1/auth/register').send({username:`user_${suffix}`,password:'a-secure-password',nickname:`用户${suffix}`,phone:`13800138${String(suffix).padStart(3,'0')}`,profile}); return response.body.data.accessToken; }

describe('health page APIs',()=>{
 let db,app,token,otherToken;
 beforeEach(async()=>{db=createTestDatabase();app=createApp({config:testConfig,db});db.prepare("INSERT INTO food_library (name,calorie_kcal,protein_g,water_ml,category,season,unit_basis) VALUES ('燕麦片',367,15,10,'grain','all','per_100g')").run(); token=await register(app,1);otherToken=await register(app,2);});
 it('reads and updates only the authenticated health profile',async()=>{const current=await request(app).get('/api/v1/profile').set('Authorization',`Bearer ${token}`);const updated=await request(app).patch('/api/v1/profile').set('Authorization',`Bearer ${token}`).send({weightKg:60});expect(current.status).toBe(200);expect(updated.body.data.bmi).toBe(22.04);expect((await request(app).patch('/api/v1/profile').set('Authorization',`Bearer ${token}`).send({})).status).toBe(400);});
 it('exposes the food catalog without a token',async()=>{const list=await request(app).get('/api/v1/foods?category=grain');const item=await request(app).get('/api/v1/foods/1');expect(list.status).toBe(200);expect(list.body.data.items[0].name).toBe('燕麦片');expect(item.body.data.unitBasis).toBe('per_100g');});
 it('creates food records, reads their view summary, and rejects wrong units',async()=>{const created=await request(app).post('/api/v1/food-records').set('Authorization',`Bearer ${token}`).send({foodId:1,mealType:'breakfast',amount:80,amountUnit:'g',intakeDate:'2026-07-17'});const summary=await request(app).get('/api/v1/food-records/daily-summary?date=2026-07-17').set('Authorization',`Bearer ${token}`);const wrong=await request(app).post('/api/v1/food-records').set('Authorization',`Bearer ${token}`).send({foodId:1,mealType:'breakfast',amount:80,amountUnit:'ml',intakeDate:'2026-07-17'});expect(created.status).toBe(201);expect(summary.body.data[0].totalCalorieKcal).toBe(293.6);expect(wrong.status).toBe(400);});
 it('scopes water records to their owner and reports a summary',async()=>{const created=await request(app).post('/api/v1/water-records').set('Authorization',`Bearer ${token}`).send({amountMl:500,intakeTime:'2026-07-17 09:00:00'});const id=created.body.data.id;const foreign=await request(app).get(`/api/v1/water-records/${id}`).set('Authorization',`Bearer ${otherToken}`);const summary=await request(app).get('/api/v1/water-records/daily-summary?date=2026-07-17').set('Authorization',`Bearer ${token}`);expect(foreign.status).toBe(404);expect(summary.body.data[0]).toMatchObject({totalWaterMl:500,drinkTimes:1});});
 it('creates, updates, and deletes sport records',async()=>{const created=await request(app).post('/api/v1/sport-records').set('Authorization',`Bearer ${token}`).send({sportType:'慢跑',durationMin:30,recordDate:'2026-07-17'});const changed=await request(app).patch(`/api/v1/sport-records/${created.body.data.id}`).set('Authorization',`Bearer ${token}`).send({durationMin:40});const deleted=await request(app).delete(`/api/v1/sport-records/${created.body.data.id}`).set('Authorization',`Bearer ${token}`);expect(changed.body.data.durationMin).toBe(40);expect(deleted.status).toBe(204);});
 it('requires a valid overnight sleep record and exposes its summary',async()=>{const invalid=await request(app).post('/api/v1/sleep-records').set('Authorization',`Bearer ${token}`).send({sleepTime:'2026-07-17 23:00:00',wakeTime:'2026-07-17 07:00:00',qualityScore:80,recordDate:'2026-07-17'});const created=await request(app).post('/api/v1/sleep-records').set('Authorization',`Bearer ${token}`).send({sleepTime:'2026-07-16 23:00:00',wakeTime:'2026-07-17 07:00:00',qualityScore:80,recordDate:'2026-07-17'});const summary=await request(app).get('/api/v1/sleep-records/daily-summary?date=2026-07-17').set('Authorization',`Bearer ${token}`);expect(invalid.status).toBe(400);expect(created.status).toBe(201);expect(summary.body.data[0]).toMatchObject({sleepHours:8,sleepQualityScore:80});});
});
